# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: https://dwlarson10.github.io/
baseurl: /
title: Dan Larson
author: Dan Larson
description: Personal blog and resume
avatar: profile.png
email: dwlarson10@gmail.com
github: dwlarson10 # username
twitter: datadanlarson
linkedin: datadanlarson
stackoverflow: user:8696245   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus: username
google_analytics: UA-63826812-4


# needed for travis-ci build
exclude: [vendor]
